// Real Tiny ERP OAuth2 connect flow — step 1 (authorize).
//
// GET ?tenant_id=...&client_id=...&client_secret=...&redirect_uri=...
//   -> 302 redirect to `${TINY_OAUTH_AUTHORIZE_URL}?response_type=code&client_id=...
//      &redirect_uri=...&state=<fresh anti-CSRF state>`
//
// TINY_OAUTH_AUTHORIZE_URL is read from env, never hardcoded — pointing it at
// tiny-mock-authorize (dev) vs. the real Tiny OAuth server is a one-line env
// change, no code change (docs/03-INTEGRACAO-TINY-ERP.md §1: real API is
// OAuth2, client_id/client_secret per tenant, generated by the tenant in
// their own Tiny account — never a single "master" credential for our app).
//
// client_secret is encrypted at rest via Supabase Vault the moment it's
// received (see .planning/PROJECT.md Key Decisions: "Segredos em repouso via
// Supabase Vault (não Fernet)") — it never touches disk in plaintext, not
// even transiently in this pending-state row.
//
// KNOWN SCOPE GAP (quick-260802-oauth-mock, documented in
// .planning/quick/260802-oauth-mock/): tenant_id is trusted from a query
// param rather than derived from an authenticated Supabase session, because
// no dashboard/"connect" button exists yet to originate an authenticated
// call. verify_jwt = false reflects this. Wiring this to a real tenant
// session (deriving tenant_id server-side, never client-supplied) is
// required before this endpoint is production-safe — building that dashboard
// flow was explicitly out of scope for this session.
import { sql } from "../_shared/db.ts";

const STATE_TTL_MS = 10 * 60 * 1000;

Deno.serve(async (req) => {
  const url = new URL(req.url);
  const tenantId = url.searchParams.get("tenant_id");
  const clientId = url.searchParams.get("client_id");
  const clientSecret = url.searchParams.get("client_secret");
  const redirectUri = url.searchParams.get("redirect_uri");

  if (!tenantId || !clientId || !clientSecret || !redirectUri) {
    return jsonError(
      "invalid_request: tenant_id, client_id, client_secret, redirect_uri are all required",
      400,
    );
  }
  if (!isValidUrl(redirectUri)) {
    return jsonError("invalid_request: redirect_uri is malformed", 400);
  }

  const authorizeBaseUrl = Deno.env.get("TINY_OAUTH_AUTHORIZE_URL");
  if (!authorizeBaseUrl) {
    console.error("tiny-oauth-authorize: TINY_OAUTH_AUTHORIZE_URL is unset");
    return jsonError("server_error", 500);
  }

  try {
    const tenantRows = await sql`select 1 from tenants where id = ${tenantId}`;
    if (tenantRows.length === 0) {
      return jsonError("tenant_not_found", 404);
    }

    const state = crypto.randomUUID();
    const expiresAt = new Date(Date.now() + STATE_TTL_MS).toISOString();

    const [{ id: vaultSecretId }] = await sql`
      select vault.create_secret(
        ${clientSecret},
        null,
        ${"tiny_oauth_states pending client_secret, state=" + state}
      ) as id
    `;

    await sql`
      insert into tiny_oauth_states
        (tenant_id, client_id, encrypted_client_secret, redirect_uri, state, expires_at)
      values
        (${tenantId}, ${clientId}, ${vaultSecretId}, ${redirectUri}, ${state}, ${expiresAt})
    `;

    const location = new URL(authorizeBaseUrl);
    location.searchParams.set("response_type", "code");
    location.searchParams.set("client_id", clientId);
    location.searchParams.set("redirect_uri", redirectUri);
    location.searchParams.set("state", state);

    return new Response(null, {
      status: 302,
      headers: { Location: location.toString() },
    });
  } catch (err) {
    // Never log clientSecret or the vault secret value itself.
    console.error("tiny-oauth-authorize failed", err);
    return jsonError("server_error", 500);
  }
});

function isValidUrl(value: string): boolean {
  try {
    new URL(value);
    return true;
  } catch {
    return false;
  }
}

function jsonError(error: string, status: number): Response {
  return new Response(JSON.stringify({ error }), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}
